wiki/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url, include
from django.utils.importlib import import_module

from wiki.views import article, accounts
from wiki.conf import settings
from wiki.core.plugins import registry

class WikiURLPatterns(object):
    '''
    configurator for wiki urls.
    
    To customize, you can define your own subclass, either overriding
    the view providers, or overriding the functions that collect
    views.
    '''

    # basic views
    article_view_class = article.ArticleView
    article_create_view_class = article.Create
    article_delete_view_class = article.Delete
    article_deleted_view_class = article.Deleted
    article_dir_view_class = article.Dir
    article_edit_view_class = article.Edit
    article_preview_view_class = article.Preview
    article_history_view_class = article.History
    article_settings_view_class = article.Settings
    article_source_view_class = article.Source
    article_plugin_view_class = article.Plugin
    revision_change_view = 'wiki.views.article.change_revision'
    revision_merge_view = 'wiki.views.article.merge'

    create_root = 'wiki.views.article.root_create'
    search_view_class = article.SearchView
    article_diff_view = 'wiki.views.article.diff'

    # account views
    signup_view_class = accounts.Signup
    login_view_class = accounts.Login
    logout_view_class = accounts.Logout

    def get_urls(self):
        urlpatterns = self.get_root_urls()
        urlpatterns += self.get_accounts_urls()
        urlpatterns += self.get_revision_urls()
        urlpatterns += self.get_article_urls()
        urlpatterns += self.get_plugin_urls()
        
        # This ALWAYS has to be the last of all the patterns since
        # the paths in theory could wrongly match other targets.
        urlpatterns += self.get_article_path_urls()
        return urlpatterns

    def get_root_urls(self):
        urlpatterns = patterns('',
            url('^$', self.article_view_class.as_view(), name='root', kwargs={'path': ''}),
            url('^create-root/$', self.create_root, name='root_create'),
            url('^_search/$', self.search_view_class.as_view(), name='search'),
            url('^_revision/diff/(?P<revision_id>\d+)/$', self.article_diff_view, name='diff'),
       )
        return urlpatterns

    def get_accounts_urls(self):
        urlpatterns = patterns('',
            url('^_accounts/sign-up/$', self.signup_view_class.as_view(), name='signup'),
            url('^_accounts/logout/$', self.logout_view_class.as_view(), name='logout'),
            url('^_accounts/login/$', self.login_view_class.as_view(), name='login'),
           )
        return urlpatterns

    def get_revision_urls(self):
        urlpatterns = patterns('',
            # This one doesn't work because it don't know where to redirect after...   
            url('^_revision/change/(?P<article_id>\d+)/(?P<revision_id>\d+)/$', self.revision_change_view, name='change_revision'),
            url('^_revision/preview/(?P<article_id>\d+)/$', self.article_preview_view_class.as_view(), name='preview_revision'),
            url('^_revision/merge/(?P<article_id>\d+)/(?P<revision_id>\d+)/preview/$', self.revision_merge_view, name='merge_revision_preview', kwargs={'preview': True}),
           )
        return urlpatterns

    def get_article_urls(self):
        urlpatterns = patterns('',
            # Paths decided by article_ids
            url('^(?P<article_id>\d+)/$', self.article_view_class.as_view(), name='get'),
            url('^(?P<article_id>\d+)/delete/$', self.article_delete_view_class.as_view(), name='delete'),
            url('^(?P<article_id>\d+)/deleted/$', self.article_deleted_view_class.as_view(), name='deleted'),
            url('^(?P<article_id>\d+)/edit/$', self.article_edit_view_class.as_view(), name='edit'),
            url('^(?P<article_id>\d+)/preview/$', self.article_preview_view_class.as_view(), name='preview'),
            url('^(?P<article_id>\d+)/history/$', self.article_history_view_class.as_view(), name='history'),
            url('^(?P<article_id>\d+)/settings/$', self.article_settings_view_class.as_view(), name='settings'),
            url('^(?P<article_id>\d+)/source/$', self.article_source_view_class.as_view(), name='source'),
            url('^(?P<article_id>\d+)/revision/change/(?P<revision_id>\d+)/$', self.revision_change_view, name='change_revision'),
            url('^(?P<article_id>\d+)/revision/merge/(?P<revision_id>\d+)/$', self.revision_merge_view, name='merge_revision'),
            url('^(?P<article_id>\d+)/plugin/(?P<slug>\w+)/$', self.article_plugin_view_class.as_view(), name='plugin'),
           )
        return urlpatterns

    def get_article_path_urls(self):
        urlpatterns = patterns('',
            # Paths decided by URLs
            url('^(?P<path>.+/|)_create/$', self.article_create_view_class.as_view(), name='create'),
            url('^(?P<path>.+/|)_delete/$', self.article_delete_view_class.as_view(), name='delete'),
            url('^(?P<path>.+/|)_deleted/$', self.article_deleted_view_class.as_view(), name='deleted'),
            url('^(?P<path>.+/|)_edit/$', self.article_edit_view_class.as_view(), name='edit'),
            url('^(?P<path>.+/|)_preview/$', self.article_preview_view_class.as_view(), name='preview'),
            url('^(?P<path>.+/|)_history/$', self.article_history_view_class.as_view(), name='history'),
            url('^(?P<path>.+/|)_dir/$', self.article_dir_view_class.as_view(), name='dir'),
            url('^(?P<path>.+/|)_settings/$', self.article_settings_view_class.as_view(), name='settings'),
            url('^(?P<path>.+/|)_source/$', self.article_source_view_class.as_view(), name='source'),
            url('^(?P<path>.+/|)_revision/change/(?P<revision_id>\d+)/$', self.revision_change_view, name='change_revision'),
            url('^(?P<path>.+/|)_revision/merge/(?P<revision_id>\d+)/$', self.revision_merge_view, name='merge_revision'),
            url('^(?P<path>.+/|)_plugin/(?P<slug>\w+)/$', self.article_plugin_view_class.as_view(), name='plugin'),
            # This should always go last!
            url('^(?P<path>.+/|)$', self.article_view_class.as_view(), name='get'),
           )
        return urlpatterns

    def get_plugin_urls(self):
        urlpatterns = patterns('',)
        for plugin in registry.get_plugins().values():
            slug = getattr(plugin, 'slug', None)
            if slug:
                article_urlpatterns = plugin.urlpatterns.get('article', [])
                urlpatterns += patterns('',
                    url('^(?P<article_id>\d+)/plugin/' + slug + '/', include(article_urlpatterns)),
                    url('^(?P<path>.+/|)_plugin/' + slug + '/', include(article_urlpatterns)),
                )
                root_urlpatterns = plugin.urlpatterns.get('root', [])
                urlpatterns += patterns('',
                    url('^_plugin/' + slug + '/', include(root_urlpatterns)),
               )
        return urlpatterns

def get_pattern(app_name="wiki", namespace="wiki", url_config_class=None):
    """Every url resolution takes place as "wiki:view_name".
       You should not attempt to have multiple deployments of the wiki in a
       single Django project.
       https://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-reversing-url-namespaces
    """
    if url_config_class is None:
        url_config_classname=getattr(settings, 'URL_CONFIG_CLASS', None)
        if url_config_classname is None:
            url_config_class = WikiURLPatterns
        else:
            url_config_modname, config_classname=url_config_classname.rsplit('.', 1)
            url_config_mod = import_module(url_config_modname)
            url_config_class = getattr(url_config_mod, config_classname)
    urlpatterns = url_config_class().get_urls()
    return urlpatterns, app_name, namespace

wiki/views/article.py
# -*- coding: utf-8 -*-
import difflib

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template.context import RequestContext
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import FormView
from django.views.generic.list import ListView

from wiki.views.mixins import ArticleMixin
from wiki import editors, forms, models
from wiki.conf import settings
from wiki.core.plugins import registry as plugin_registry
from wiki.core.diff import simple_merge
from wiki.decorators import get_article, json_view
from django.core.urlresolvers import reverse
from django.db import transaction
from wiki.core.exceptions import NoRootURL
from wiki.core import permissions
from django.http import Http404

class ArticleView(ArticleMixin, TemplateView):

    template_name="wiki/view.html"
    
    @method_decorator(get_article(can_read=True))
    def dispatch(self, request, article, *args, **kwargs):
        return super(ArticleView, self).dispatch(request, article, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        kwargs['selected_tab'] = 'view'
        return ArticleMixin.get_context_data(self, **kwargs)

class Create(FormView, ArticleMixin):
    
    form_class = forms.CreateForm
    template_name="wiki/create.html"
    
    @method_decorator(get_article(can_write=True, can_create=True))
    def dispatch(self, request, article, *args, **kwargs):
            
        return super(Create, self).dispatch(request, article, *args, **kwargs)
    
    def get_form(self, form_class):
        """
        Returns an instance of the form to be used in this view.
        """
        kwargs = self.get_form_kwargs()
        initial = kwargs.get('initial', {})
        initial['slug'] = self.request.GET.get('slug', None)
        kwargs['initial'] = initial
        form = form_class(self.request, self.urlpath, **kwargs)
        form.fields['slug'].widget = forms.TextInputPrepend(prepend='/'+self.urlpath.path)        
        return form
    
    @transaction.commit_manually
    def form_valid(self, form):
        user=None
        ip_address = None
        if not self.request.user.is_anonymous():
            user = self.request.user
            if settings.LOG_IPS_USERS:
                ip_address = self.request.META.get('REMOTE_ADDR', None)
        elif settings.LOG_IPS_ANONYMOUS:
            ip_address = self.request.META.get('REMOTE_ADDR', None)
        try:
            self.newpath = models.URLPath.create_article(
                self.urlpath,
                form.cleaned_data['slug'],
                title=form.cleaned_data['title'],
                content=form.cleaned_data['content'],
                user_message=form.cleaned_data['summary'],
                user=user,
                ip_address=ip_address,
                article_kwargs={'owner': user,
                                'group': self.article.group,
                                'group_read': self.article.group_read,
                                'group_write': self.article.group_write,
                                'other_read': self.article.other_read,
                                'other_write': self.article.other_write,
                                })
            messages.success(self.request, _(u"New article '%s' created.") % self.newpath.article.current_revision.title)
        
            transaction.commit()
        # TODO: Handle individual exceptions better and give good feedback.
        except Exception, e:
            transaction.rollback()
            if self.request.user.is_superuser:
                messages.error(self.request, _(u"There was an error creating this article: %s") % str(e))
            else:
                messages.error(self.request, _(u"There was an error creating this article."))
            transaction.commit()
            return redirect('wiki:get', '')
            
        url = self.get_success_url()
        transaction.commit()
        return url
    
    def get_success_url(self):
        return redirect('wiki:get', self.newpath.path)
    
    def get_context_data(self, **kwargs):
        kwargs['parent_urlpath'] = self.urlpath
        kwargs['parent_article'] = self.article
        kwargs['create_form'] = kwargs.pop('form', None)
        kwargs['editor'] = editors.getEditor()
        return super(Create, self).get_context_data(**kwargs)
    

class Delete(FormView, ArticleMixin):
    
    form_class = forms.DeleteForm
    template_name="wiki/delete.html"
    
    @method_decorator(get_article(can_write=True, not_locked=True, can_delete=True))
    def dispatch(self, request, article, *args, **kwargs):
        return self.dispatch1(request, article, *args, **kwargs)
        
    def dispatch1(self, request, article, *args, **kwargs):
        """Deleted view needs to access this method without a decorator,
        therefore it is separate."""
        urlpath = kwargs.get('urlpath', None)
        # Where to go after deletion... 
        self.next = ""
        self.cannot_delete_root = False
        if urlpath and urlpath.parent:
            self.next = reverse('wiki:get', kwargs={'path': urlpath.parent.path})
        elif urlpath:
            # We are a urlpath with no parent. This is the root
            self.cannot_delete_root = True
        else:
            # We have no urlpath. Get it if a urlpath exists
            for art_obj in article.articleforobject_set.filter(is_mptt=True):
                if art_obj.content_object.parent:
                    self.next = reverse('wiki:get', kwargs={'article_id': art_obj.content_object.parent.article.id})
                else:
                    self.cannot_delete_root = True
        
        return super(Delete, self).dispatch(request, article, *args, **kwargs)
    
    def get_initial(self):
        return {'revision': self.article.current_revision}
    
    def get_form(self, form_class):
        form = super(Delete, self).get_form(form_class)
        if self.article.can_moderate(self.request.user):
            form.fields['purge'].widget = forms.forms.CheckboxInput()
        return form
    
    def get_form_kwargs(self):
        kwargs = FormView.get_form_kwargs(self)
        kwargs['article'] = self.article
        kwargs['has_children'] = bool(self.children_slice)
        return kwargs
        
    def form_valid(self, form):
        cd = form.cleaned_data
        
        purge = cd['purge']
        
        #If we are purging, only moderators can delete articles with children
        cannot_delete_children = False
        can_moderate = self.article.can_moderate(self.request.user)
        if purge and self.children_slice and not can_moderate:
            cannot_delete_children = True

        if self.cannot_delete_root or cannot_delete_children:
            messages.error(self.request, _(u'This article cannot be deleted because it has children or is a root article.'))
            return redirect('wiki:get', article_id=self.article.id)
        

        if can_moderate and purge:
            # First, remove children
            if self.urlpath:
                self.urlpath.delete_subtree()
            self.article.delete()
            messages.success(self.request, _(u'This article together with all its contents are now completely gone! Thanks!'))
        else:
            revision = models.ArticleRevision()
            revision.inherit_predecessor(self.article)
            revision.set_from_request(self.request)
            revision.deleted = True
            self.article.add_revision(revision)
            messages.success(self.request, _(u'The article "%s" is now marked as deleted! Thanks for keeping the site free from unwanted material!') % revision.title)
        return self.get_success_url()
        
    def get_success_url(self):
        return redirect(self.next)
    
    def get_context_data(self, **kwargs):
        cannot_delete_children = False
        if self.children_slice and not self.article.can_moderate(self.request.user):
            cannot_delete_children = True
        
        kwargs['delete_form'] = kwargs.pop('form', None)
        kwargs['cannot_delete_root'] = self.cannot_delete_root
        kwargs['delete_children'] = self.children_slice[:20]
        kwargs['delete_children_more'] = len(self.children_slice) > 20
        kwargs['cannot_delete_children'] = cannot_delete_children
        return super(Delete, self).get_context_data(**kwargs)


class Edit(FormView, ArticleMixin):
    """Edit an article and process sidebar plugins."""
    
    form_class = forms.EditForm
    template_name="wiki/edit.html"
    
    @method_decorator(get_article(can_write=True, not_locked=True))
    def dispatch(self, request, article, *args, **kwargs):
        self.sidebar_plugins = plugin_registry.get_sidebar()
        self.sidebar = []
        return super(Edit, self).dispatch(request, article, *args, **kwargs)
    
    def get_initial(self):
        initial = FormView.get_initial(self)
        
        for field_name in ['title', 'content']:
            session_key = 'unsaved_article_%s_%d' % (field_name, self.article.id)
            if session_key in self.request.session.keys():
                content = self.request.session[session_key]
                initial[field_name] = content
                del self.request.session[session_key]
        return initial
    
    def get_form(self, form_class):
        """
        Checks from querystring data that the edit form is actually being saved,
        otherwise removes the 'data' and 'files' kwargs from form initialisation.
        """
        kwargs = self.get_form_kwargs()
        if self.request.POST.get('save', '') != '1' and self.request.POST.get('preview') != '1':

wiki/templates/wiki/base.html
{% load sekizai_tags i18n wiki_tags %}{% load url from future %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block wiki_pagetitle %}{% endblock %} - Anonimous wiki</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="www.django-wiki.org">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}wiki/bootstrap/css/wiki-bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}wiki/bootstrap/css/wiki-bootstrap-responsive.min.css" rel="stylesheet">
        
    {% render_block "css" %}
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>

    {% block wiki_body %}
    
    {% block wiki_navbar %}
    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          {% block wiki_header_branding %}
          <a class="brand" href="{% url 'wiki:root' %}">Anonimous-\/\/  i K |</a>
          {% endblock %}
          <form class="navbar-search pull-right" id="navbar_wiki_search" method="GET" action="{% url 'wiki:search' %}">
            <span class="icon-search"></span>
            <input type="text" name="query" class="search-query" placeholder="{% trans "Search..." %}" />
          </form>
          <div class="pull-right">
            {% if user.is_authenticated %}
            <ul class="nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="badge notification-cnt">0</span>
                  {{ user }}
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url 'wiki:logout' %}">
                      <i class="icon-off"></i>
                      {% trans "Log out" %}
                    </a>
                  </li>
                  {% include "wiki/plugins/notifications/menubaritem.html" %}
                </ul>
              </li>
            </ul>
            {% else %}
            <ul class="nav">
              <li>
                <a href="{% login_url as wiki_login_url %}{{ wiki_login_url }}">{% trans "Log in" %}</a>
              </li>
              <li>
                <a href="{% url 'wiki:signup' %}">{% trans "Sign up" %}</a>
              </li>
            </ul>
            {% endif %}
          </div>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/">{% trans "Home" %}</a></li>
              <li><a href="https://github.com/benjaoming/django-wiki" target="_blank">{% trans "About" %}</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

    <div class="container" style="margin-top: 60px;">

      {% if messages %}
        <!-- Messages for this instance -->
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

      <!-- Reserved for breadcrumbs -->
      {% block wiki_breadcrumbs %}{% endblock %}
      
      <!-- Main page contents go here -->
      {% block wiki_contents %}{% endblock %}
      
      <footer id="wiki-footer">
        <hr />
        {% block wiki_footer_logo %}
        <a href="https://github.com/benjaoming/django-wiki" class="pull-right"><img src="{{ STATIC_URL }}wiki/img/github_icon.png" /></a>
        {% endblock %}
        {% block wiki_footer_prepend %}
        {% endblock %}
        <p>{% blocktrans %}Open source application under the <a href="http://www.gnu.org/licenses/quick-guide-gplv3.html">GPLv3</a> license. Let knowledge be the cure.{% endblocktrans %}</p>
        <div style="clear: both"></div>
      </footer>
      </div>

    </div> <!-- /container -->

    {% endblock %}

    <script src="{{ STATIC_URL }}wiki/js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}wiki/js/core.js"></script>
    <script src="{{ STATIC_URL }}wiki/bootstrap/js/bootstrap.min.js"></script>
    {% render_block "js" %}
  
  </body>
</html>

wiki/templates/wiki/history.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n sekizai_tags %}
{% load url from future %}

{% block wiki_pagetitle %}{% trans "History" %}: {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% include "wiki/includes/modals.html" %}

{% addtoblock "js" %}
<script type="text/javascript" src="{{ STATIC_URL }}wiki/js/diffview.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}wiki/js/diff.js"></script>
{% endaddtoblock %}
{% addtoblock "css" %}
<style type="text/css">
  td.linenumber {
    width: 20px;
  }
  tr.insert td {
    background-color: #DFC;
  }
  tr.delete td {
    background-color: #FDC;
  }
  tr.equal td {
    background-color: #F2F2F2;
  }
  
  .diff-container td {
    white-space: pre; font-family: monospace;
  }
  .diff-container td,
  .diff-container th {
    padding: 2px 7px;
    border-right: 1px solid #DDD;    
  }
  .diff-container td:last-child,
  .diff-container th:last-child {
    border-right: none;
  }
  .diff-container table {
    border-top: 1px solid #DDD;    
  }
</style>
{% endaddtoblock %}

<p class="lead">
  {% trans "Click each revision to see a list of edited lines. Click the Preview button to see how the article looked at this stage. At the bottom of this page, you can change to a particular revision or merge an old revision with the current one." %}
</p>

<form method="GET">
  <div class="tab-content" style="overflow: visible;">
    {% for revision in revisions %}
      <div class="accordion" id="accordion{{ revision.revision_number }}">
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" style="float: left;" href="#collapse{{ revision.revision_number }}" onclick="get_diff_json('{% url 'wiki:diff' revision.id %}', $('#collapse{{ revision.revision_number }}'))">
              {% if revision == article.current_revision %}
                <i class="icon-flag"></i>
              {% else %}
                <i class="icon-plus"></i>
              {% endif %}
              {% include "wiki/includes/revision_info.html" with current_revision=article.current_revision %}
              <div style="color: #CCC;">
                <small>
                {% if revision.user_message %}
                  {{ revision.user_message }}
                {% elif revision.automatic_log %}
                  {{ revision.automatic_log }}
                {% else %}
                  ({% trans "no log message" %})
                {% endif %}
                </small>
              </div>
            </a>
            <div class="progress progress-striped active" style="display: none; width: 40px; float: left; margin-top: 7px; margin-bottom: -7px;">
              <div class="bar" style="width: 100%;"></div>
            </div>
            <div class="pull-right" style="vertical-align: middle; margin: 8px 8px;">
              {% if revision == article.current_revision %}
              <a href="#" class="btn disabled">
                <span class="icon-lock"></span>
                {% trans "Preview this revision" %}
              </a>
              {% else %}
              <button type="submit" class="btn" onclick="$('#previewModal').modal('show'); this.form.target='previewWindow'; this.form.r.value='{{ revision.id }}'; this.form.action='{% url 'wiki:preview_revision' article.id %}'; $('#previewModal .switch-to-revision').attr('href', '{% url 'wiki:change_revision' path=urlpath.path article_id=article.id revision_id=revision.id %}')">
                <span class="icon-eye-open"></span>
                {% trans "Preview this revision" %}
              </button>
              {% endif %}
              
              {% if article|can_write:user and not article.current_revision.locked %}
              <input type="radio"{% if revision == article.current_revision %} disabled="true"{% endif %} style="margin: 0 10px;" value="{{ revision.id }}" name="revision_id" switch-button-href="{% url 'wiki:change_revision' path=urlpath.path revision_id=revision.id %}" merge-button-href="{% url 'wiki:merge_revision_preview' article_id=article.id revision_id=revision.id %}" merge-button-commit-href="{% url 'wiki:merge_revision' path=urlpath.path article_id=article.id revision_id=revision.id %}" />
              {% endif %}
              
            </div>
            <div style="clear: both"></div>
          </div>
          <div id="collapse{{ revision.revision_number }}" class="accordion-body collapse">
            <div class="accordion-inner diff-container" style="padding: 0;">
              <dl class="dl-horizontal">
                <dt>{% trans "Auto log:" %}</dt>
                <dd>{{ revision.automatic_log|default:"-"|linebreaksbr }}</dd>
              </dl>
              <table class="table table-condensed" style="margin: 0; border-collapse: collapse;">
                <thead>
                  <tr>
                    <th class="linenumber">{% if revision.previous_revision %}#{{revision.previous_revision.revision_number}}{% endif %}</th>
                    <th class="linenumber">#{{revision.revision_number}}</th>
                    <th>{% trans "Change" %}</th>
                  </tr>
                </thead>
              </table>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    
    {% include "wiki/includes/pagination.html" %}
    
    {% if revisions.count > 1 and article|can_write:user and not article.current_revision.locked %}

    <div class="form-actions">
      <div class="pull-right">
        <button type="submit" name="preview" value="1" class="btn btn-large" onclick="$('#mergeModal').modal('show'); this.form.target='mergeWindow'; this.form.action=$('input[type=radio]:checked').attr('merge-button-href'); $('.merge-revision-commit').attr('href', $('input[type=radio]:checked').attr('merge-button-commit-href'))">
          <span class="icon-random"></span>
          {% trans "Merge selected with current..." %}
        </button>
        <button type="submit" name="save" value="1" class="btn btn-large btn-primary" onclick="this.form.target='_self'; this.form.action=$('input[type=radio]:checked').attr('switch-button-href')">
          <span class="icon-flag"></span>
          {% trans "Switch to selected version" %}
        </button>
      </div>
    </div>
    
    {% endif %}
    
  </div>
  <input type="hidden" name="r" value="" />
  <div class="modal hide wiki-modal" id="previewModal">
    <div class="modal-body">
      <iframe name="previewWindow" frameborder="0"></iframe>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn btn-large" data-dismiss="modal">
        <span class="icon-circle-arrow-left"></span>
        {% trans "Back to history view" %}
      </a>
      {% if article|can_write:user %}
      <a href="#" class="btn btn-large btn-primary switch-to-revision">
        <span class="icon-flag"></span>
        {% trans "Switch to this version" %}
      </a>
      {% else %}
        <a href="#" class="btn btn-large btn-primary disabled">
          <span class="icon-lock"></span>
          {% trans "Switch to this version" %}
        </a>                    
      {% endif %}
    </div>
  </div>

  <div class="modal hide wiki-modal" id="mergeModal">
    <div class="modal-header">
      <h1>{% trans "Merge with current" %}</h1>
      <p class="lead"><span class="icon-info-sign"></span> {% trans "When you merge a revision with the current, all data will be retained from both versions and merged at its approximate location from each revision." %} <strong>{% trans "After this, it's important to do a manual review." %}</strong></p>
    </div>
    <div class="modal-body">
      <iframe name="mergeWindow" frameborder="0" style="min-height: 0;"></iframe>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn btn-large" data-dismiss="modal">
        <span class="icon-circle-arrow-left"></span>
        {% trans "Back to history view" %}
      </a>
      {% if article|can_write:user %}
      <a href="#" class="btn btn-large btn-primary merge-revision-commit">
        <span class="icon-file"></span>
        {% trans "Create new merged version" %}
      </a>                    
      {% else %}
        <a href="#" class="btn btn-large btn-primary disabled">
          <span class="icon-lock"></span>
          {% trans "Create new merged version" %}
        </a>                    
      {% endif %}
    </div>
  </div>
</form>
  
{% endblock %}

wiki/templates/wiki/permission_denied.html
{% extends "wiki/base.html" %}
{% load wiki_tags i18n %}
{% load url from future %}

{% block wiki_pagetitle %}Permission Denied{% endblock %}

{% block wiki_contents %}
  <h1 class="page-header">{% trans "Permission Denied" %}</h1>
  <p class="alert denied alert-error">
    <i class="icon-minus-sign"></i>
    {% trans "Sorry, you don't have permission to access this page." %}
  </p>
  {% if article.current_revision.locked %}
  <p class="alert alert-warning">
    <i class="icon-lock"></i>
    {% trans "This article is locked for editing." %}
  </p>
  {% endif %}
  
  <p>
    <a href="{% url 'wiki:get' article_id=article.id path=urlpath.path %}" class="btn">
      {% trans "Back to article" %}
    </a>
  </p>
  
{% endblock %}